name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install openssh-client

    - name: Use SSH key for authentication
      run: |
        echo "$SSH_PUBLIC_KEY" > ssh_key
        chmod 600 ssh_key
        ssh -o StrictHostKeyChecking=no -i ssh_key root@159.203.160.8 'bash -s' < /root/dish-discovery/.github/scripts/deploy.sh

