name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deployment script
        run: |
          cd /root/dish-discovery/
          chmod +x deploy.sh
          ./deploy.sh

